export const DEFAULTS = {
    type: "primary",
    label: "Button",
    bgColor: "#FFA500",
    textColor: "#000",
    fontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    fontSize: "16px",
    fontWeight: "500",
    minWidth: "170px",
    height: "44px",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    /* ========= INPUT DEFAULTS (appended) ========= */
    inputType: "text",
    inputPlaceholder: "",
    inputTextColor: "#000",
    inputBgColor: "#fff",
    inputBorderColor: "#ccc",
    inputFocusBorderColor: "#06f",
    inputHeight: "44px",
    inputPadding: "8px 12px",
    inputBorderRadius: "6px",
    inputWidth: "100%",
    inputFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    inputFontSize: "16px",
    inputFontWeight: "400"
};