const DEFAULTS = {
    /* ========= INPUT DEFAULTS (appended) ========= */
    inputType: "text",
    inputPlaceholder: "",
    inputTextColor: "#000",
    inputBgColor: "#fff",
    inputBorderColor: "#ccc",
    inputFocusBorderColor: "#06f",
    inputHeight: "44px",
    inputPadding: "8px 12px",
    inputBorderRadius: "6px",
    inputWidth: "100%",
    inputFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    inputFontSize: "16px",
    inputFontWeight: "400",

    /* ========= DROPDOWN DEFAULTS (APPENDED ONLY) ========= */
    dropdownTextColor: "#000",
    dropdownBgColor: "#fff",
    dropdownBorderColor: "#ccc",
    dropdownFocusBorderColor: "#06f",
    dropdownHeight: "44px",
    dropdownPadding: "8px 12px",
    dropdownBorderRadius: "6px",
    dropdownWidth: "100%",
    dropdownFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    dropdownFontSize: "16px",
    dropdownFontWeight: "400",
    dropdownCursor: "pointer",


    /* ========= BUTTON DEFAULTS ========= */
    type: "primary",
    label: "Button",
    bgColor: "#FFA500",
    textColor: "#000",
    fontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    fontSize: "16px",
    fontWeight: "500",
    minWidth: "170px",
    height: "44px",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",

    /* ========= INPUT DEFAULTS ========= */
    inputType: "text",
    inputPlaceholder: "",
    inputTextColor: "#000",
    inputBgColor: "#fff",
    inputBorderColor: "#ccc",
    inputFocusBorderColor: "#06f",
    inputHeight: "44px",
    inputPadding: "8px 12px",
    inputBorderRadius: "6px",
    inputWidth: "100%",
    inputFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    inputFontSize: "16px",
    inputFontWeight: "400",

    /* ========= TABLE DEFAULTS ========= */
    tableWidth: "100%",
    tableFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    tableFontSize: "14px",
    tableBorderColor: "#ddd",
    tableHeaderBg: "#f5f5f5",
    tableHeaderTextColor: "#000",
    tableRowHoverBg: "#fafafa",
    tablePadding: "10px",
    tableTextColor: "#000",

    /* ========= SEARCH / FILTER DEFAULTS ========= */
    tableSearchEnabled: true,
    tableFilterEnabled: true,
    searchPlaceholder: "Search...",
    filterPlaceholder: "Select column",

    /* ========= TABLE INPUT OVERRIDES ========= */
    tableInputHeight: "36px",
    tableInputPadding: "6px 10px",
    tableInputBorderRadius: "4px",
    tableInputBorderColor: "#ccc",
    tableInputFocusBorderColor: "#06f",
    tableInputFontSize: "14px",
    /* ========= RADIO BUTTON DEFAULTS (APPENDED ONLY) ========= */
    radioGap: "8px",
    radioGroupGap: "12px",
    radioTextColor: "#000",
    radioFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    radioFontSize: "16px",
    radioFontWeight: "400",
    radioCursor: "pointer",
    /* ========= CHECKBOX DEFAULTS (APPENDED ONLY) ========= */
    checkboxGap: "8px",
    checkboxGroupGap: "12px",
    checkboxTextColor: "#000",
    checkboxFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    checkboxFontSize: "16px",
    checkboxFontWeight: "400",
    checkboxCursor: "pointer",

    /* ========= DATEPICKER DEFAULTS (APPENDED ONLY) ========= */
    dateInputType: "date",
    dateWidth: "100%",
    dateHeight: "44px",
    datePadding: "8px 12px",
    dateFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
    dateFontSize: "16px",
    dateFontWeight: "400",
    dateTextColor: "#000",
    dateBgColor: "#fff",
    dateBorderColor: "#ccc",
    dateFocusBorderColor: "#06f",
    dateBorderRadius: "6px",
    dateCursor: "pointer",
    /* ========= FILE UPLOAD DEFAULTS (APPENDED ONLY) ========= */
fileInputWidth: "100%",
fileInputHeight: "44px",
fileInputPadding: "8px 12px",
fileInputBorderRadius: "6px",
fileInputBorderColor: "#ccc",
fileInputFocusBorderColor: "#06f",
fileInputBgColor: "#fff",
fileInputTextColor: "#000",
fileInputFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
fileInputFontSize: "14px",
fileInputFontWeight: "400",
fileInputCursor: "pointer",
fileHintFontSize: "12px",
fileHintTextColor: "#666",
fileHintMarginTop: "6px",
/* ========= LOADER DEFAULTS (APPENDED ONLY) ========= */
loaderSize: "40px",
loaderBorderWidth: "4px",
loaderColor: "#FFA500",
loaderBgColor: "#e0e0e0",
loaderBorderRadius: "50%",
loaderAnimationDuration: "1s",
loaderText: "Loading...",
loaderTextColor: "#000",
loaderFontFamily: "HelveticaNeueLTStd-Bd, Helvetica, Arial, sans-serif",
loaderFontSize: "14px",
loaderGap: "8px",
loaderAlignment: "center"


};

